name: Deploy to Vercel

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Only run if Vercel secrets are configured
    if: ${{ secrets.VERCEL_TOKEN }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build --workspace=apps/web
      
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-args: '--prod'
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./

  # Fallback job that runs when Vercel secrets are not configured
  build-only:
    runs-on: ubuntu-latest
    if: ${{ !secrets.VERCEL_TOKEN }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build --workspace=apps/web
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: production-build
        path: apps/web/dist/
        retention-days: 30
        
    - name: Deployment Status
      run: |
        echo "✅ Build completed successfully!"
        echo "📦 Production build artifacts uploaded"
        echo "🚀 To enable automatic deployment:"
        echo "   1. Create a Vercel account at https://vercel.com"
        echo "   2. Add VERCEL_TOKEN, VERCEL_ORG_ID, and VERCEL_PROJECT_ID to GitHub secrets"
        echo "   3. Push to main branch to trigger automatic deployment"